# Default values for test-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

envoy:
  replicaCount: 1
  service:
    type: LoadBalancer

  files:
    envoy.yaml: |-
      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901
      static_resources:
        listeners:
          - name: listener_0
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 10000
            filter_chains:
              - filters:
                  - name: envoy.http_connection_manager
                    config:
                      access_log:
                        - name: envoy.file_access_log
                          config:
                            path: /dev/stdout
                      stat_prefix: ingress_http
                      route_config:
                        name: local_route
                        virtual_hosts:
                          - name: local_service
                            domains: ["*"]
                            routes:
                              - match:
                                  prefix: "/"
                                route:
                                  host_rewrite: test-chart
                                  cluster: service_test-chart
                      http_filters:
                        - name: envoy.router
        clusters:
          - name: service_test-chart
            connect_timeout: 0.25s
            type: LOGICAL_DNS
            dns_lookup_family: V4_ONLY
            lb_policy: ROUND_ROBIN
            hosts:
              - socket_address:
                  address: test-chart
                  port_value: 80

replicaCount: 1

image:
  repository: govargo/happy-helming
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: only-echo

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: test-chart
  type: ClusterIP
  port: 80

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
